### ISSUE TITLE
Practica 6: Seguimiento de imagenes

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-tlaxroom#2]
[PRACTICA 6_ MARCADOR IMG.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-tlaxroom/files/8617488/PRACTICA.6_.MARCADOR.IMG.pdf)

**Comment by EDITH-R** [comment]
[PRACTICA 6_ MARCADOR IMG.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-tlaxroom/files/8617493/PRACTICA.6_.MARCADOR.IMG.pdf)

**Comment by DamGL** [comment]
super 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
